name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: huunghiaish/devops-zero-demo:${{ github.ref_name }}

    - name: Docker Metadata
      uses: docker/metadata-action@v3
      with:
        images: huunghiaish/devops-zero-demo
        tags: type=ref,event=branch
        github-token: ${{ secrets.GITHUB_TOKEN }}
